### ISSUE TITLE
2.7 版本的 cleaners 机制问题

### ISSUE THREAD

**Issue by wenber-yu** [huang-yi/shadowfax#24]
OS: macOS 10.15.5 (19F101)
PHP: 7.4.7
Laravel: 7.17.1

1. 文档中指出, 如果使用 `shadowfax:cleaners` 来生成清理类的话, 无需在 `shadowfax.yml` 中的 `cleaners` 进行配置.
但是我从 `2.6` 升级后, 将之前的监听器更为清理器时, 生成的清理器目录并未在 `shadowfax.yml` 自动配置.

2. 文档中关于对 `tymon/jwt-auth` 包的清理示例.
app/Cleaners/TymonJwtAuthCleaner.php
```php
    public function clean(Container $app) : void
    {
        $class    = LaravelServiceProvider::class;
        $provider = new $class;

        $method = (new ReflectionObject($provider))->getMethod('extendAuthGuard');

        $method->setAccessible(true);

        $method->invoke($provider);
    }
```
启动正常. 请求路由时, 报错如下:
```bash
2   [internal]:0
      Whoops\Run::handleShutdown()

   Whoops\Exception\ErrorException

  Uncaught ArgumentCountError: Too few arguments to function Illuminate\Support\ServiceProvider::__construct(), 0 passed in /Users/wilbur/htdocs/work/soci/app/Cleaners/TymonJwtAuthCleaner.php on line 22 and exactly 1 expected in /Users/wilbur/htdocs/work/soci/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:41
Stack trace:
#0 /Users/wilbur/htdocs/work/soci/app/Cleaners/TymonJwtAuthCleaner.php(22): Illuminate\Support\ServiceProvider->__construct()
#1 /Users/wilbur/htdocs/work/soci/vendor/huang-yi/shadowfax/src/Listeners/AppPushingEvent/RunCleaners.php(34): App\Cleaners\TymonJwtAuthCleaner->clean(Object(Illuminate\Foundation\Application))
#2 /Users/wilbur/htdocs/work/soci/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\AppPushingEvent\RunCleaners->handle(Object(HuangYi\Shadowfax\Events\AppPushingEvent))
#3 /Users/wilbur/htdocs/work/soci/vendor/huang-yi/shadowfax/src/HasEventDispatcher.php(26): HuangYi\Shadowfax\EventDispatcher->dispatch

  at vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:41
    37|      *
    38|      * @param  \Illuminate\Contracts\Foundation\Application  $app
    39|      * @return void
    40|      */
  > 41|     public function __construct($app)
    42|     {
    43|         $this->app = $app;
    44|     }
    45|

      +1 vendor frames

```

**Comment by huang-yi** [comment]
升级上去的需要手动在`shadowfax.yml`里面添加一下:

```yaml
cleaners:
  - app/Cleaners/
```

`TymonJwtAuthCleaner`在new ServiceProvider时我忘记把$app传进去了，我的疏忽：

```php
$provider = new $class($app);
```

我调整一下文档。

**Comment by wenber-yu** [comment]
嗯, 这样写也可以.
```php
$provider = $app->getProvider(LaravelServiceProvider::class);
```
但是这个方法涉及多态调用, 不太好定位. `$app` 的定义中也没有定义该方法.

**Comment by huang-yi** [comment]
之前那种写法当然是支持的，我文档里的写法主要是为了兼容Lumen，因为Lumen的Application类没有`getProvider`方法。
