### ISSUE TITLE
偶现的崩溃问题

### ISSUE THREAD

**Issue by wenber-yu** [huang-yi/shadowfax#27]
```bash
 Whoops\Exception\ErrorException

  Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w

  at vendor/huang-yi/shadowfax/src/Container.php:75
    71|         if (isset($this->bindings[$abstract])) {
    72|             return $this->instances[$abstract] = $this->bindings[$abstract]($this);
    73|         }
    74|
  > 75|         throw new EntryNotFoundException($abstract);
    76|     }
    77|
    78|     /**
    79|      * Remove a instance from the container.

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
[2020-06-25 15:57:08 *23199.1]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php on line 75
[2020-06-25 15:57:08 $20731.0]	WARNING	swManager_check_exit_status: worker#1[pid=23199] abnormal exit, status=255, signal=0
```

`php shadowfax start -w` 起动时, 在修改 `.env` 文件时, 会偶现这个问题.

**Comment by huang-yi** [comment]
看堆栈信息是在request回调里面报的错。但费解的是，app_pool在workerStart回调里就被注册到容器里面了，为什么在request回调里面却不存在。

我尝试了很多情况，都没有复现出这个报错，不知道你那边还能提供更多的信息吗？好复现一下这个问题。

**Comment by wenber-yu** [comment]
之后我会留意出现该情况时的操作, 因为最近一天我也一直都没有再复现此问题.

**Comment by wenber-yu** [comment]
```bash
[2020-06-29 15:48:44 $2788.0]	INFO	Server is reloading all workers now
The Shadowfax server reloaded.
[×] worker process stopped. [3212]
[×] worker process stopped. [3213]
PHP Fatal error:  Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php on line 75

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w

  at vendor/huang-yi/shadowfax/src/Container.php:75
    71|         if (isset($this->bindings[$abstract])) {
    72|             return $this->instances[$abstract] = $this->bindings[$abstract]($this);
    73|         }
    74|
  > 75|         throw new EntryNotFoundException($abstract);
    76|     }
    77|
    78|     /**
    79|      * Remove a instance from the container.


   Whoops\Exception\ErrorException

  Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w

  at vendor/huang-yi/shadowfax/src/Container.php:75
    71|         if (isset($this->bindings[$abstract])) {
    72|             return $this->instances[$abstract] = $this->bindings[$abstract]($this);
    73|         }
    74|
  > 75|         throw new EntryNotFoundException($abstract);
    76|     }
    77|
    78|     /**
    79|      * Remove a instance from the container.

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
[2020-06-29 15:48:44 *3755.1]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught HuangYi\Shadowfax\Exceptions\EntryNotFoundException: app_pool in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php:75
Stack trace:
#0 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/helpers.php(23): HuangYi\Shadowfax\Container->make('app_pool')
#1 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(107): shadowfax('app_pool')
#2 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/HasHelpers.php(118): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->appPool()
#3 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Listeners/RequestEvent/HandleRequest.php(30): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handleWithoutException(Object(Closure))
#4 /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/EventDispatcher.php(61): HuangYi\Shadowfax\Listeners\RequestEvent\HandleRequest->handle(Object(HuangYi\Shadowfax\Events\RequestEvent))
#5 /Users/wenber/htdocs/w in /Users/wenber/htdocs/work/socialab/vendor/huang-yi/shadowfax/src/Container.php on line 75
[2020-06-29 15:48:45 $2788.0]	WARNING	swManager_check_exit_status: worker#1[pid=3755] abnormal exit, status=255, signal=0
[√] worker process started. [3756]
[√] worker process started. [3758]
```

修改了一个工具类文件后, 程序自动重启 `worker` 的时候

**Comment by huang-yi** [comment]
看了这次的console日志，我的分析是这样的：

**首先确认一下你的网站里面是不是有轮询？** 如果有的话，我的分析应该成立。你的worker进程结束后正在重启新的worker进程（`3755`），这时前端刚好有一个轮询的请求进来了，但此时`3755`的`workerStart`回调还未执行完，也就是说`app_pool`在这一刻还未初始化，然后还被轮询触发了`request`回调，所以导致异常。好在swoole遇到异常又会重启新的进程，所以后面还是能让应用正常运行。

**Comment by wenber-yu** [comment]
是这个原因, 在自动重启的过程中, 有请求进来就会触发该异常, 感谢解答.

**Comment by huang-yi** [comment]
感谢反馈，我这边会加强一下workerStart和request之间的逻辑
